#!/usr/bin/env python3

'''
lib/util/id.py
ID generator. Uses a global counter to ensure that all numerical ID components
are unique across the whole plugin.
'''

import logging
import threading

logger = logging.getLogger('sublime-ycmd.' + __name__)

_COUNTER = 0
_LOCK = threading.RLock()


def _set_counter(counter):
    global _COUNTER
    with _LOCK:
        _COUNTER = counter


def _get_counter():
    with _LOCK:
        return _COUNTER


def _increment_counter(count=1):
    global _COUNTER
    with _LOCK:
        _COUNTER += count


def _reset_counter():
    _set_counter(0)


def generate_id(prefix=None):
    '''
    Generates and returns a `str` id.

    The id is generated by appending the `prefix` to a globally unique integer
    counter. The counter is not specific to the prefix.
    '''
    if not isinstance(prefix, str):
        raise TypeError('prefix must be a str: %r' % (prefix))

    if prefix is None:
        prefix = ''

    current_count = _get_counter()
    _increment_counter()

    return '%s%d' % (prefix, current_count)
